name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Validate Locales
        run: python .scripts/validate_locales.py
